title: Jalil Rzayev
email: ""
description: >-
  Computer science student passionate about mathematics, building clean web projects,
  and improving problem-solving skills through practical work.

# You chose A, so baseurl must be empty
baseurl: ""
url: ""

social:
  github: "https://github.com/rzayevcelil756-sudo"
  codecademy: "https://www.codecademy.com/profiles/Celil314"

# Required: link to your website repository
repo_url: "https://github.com/rzayevcelil756-sudo/rzayevcelil756-sudo.github.io"

markdown: kramdown
theme: null
plugins: []
